[enclave]
prod_id = 0
isv_svn = 0
debug = true
misc_select = 1

[mem]
heap_min_size = "512M"
heap_init_size = "512M"
heap_max_size = "128G"
stack_min_size = "32K"
stack_max_size = "256K"

[threads]
num_tcs = 128
tcs_policy = 0
